# Generated by Django 4.1.7 on 2023-04-23 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagno', models.CharField(max_length=12, unique=True)),
                ('breed', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('age', models.IntegerField(default=0)),
                ('age_years', models.IntegerField(default=0)),
                ('weight', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=40)),
                ('firstdose', models.IntegerField()),
                ('boosterdose', models.IntegerField()),
                ('subsequentdose', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=28)),
                ('lastname', models.CharField(max_length=28)),
                ('email', models.CharField(max_length=28, unique=True)),
                ('phonenumber', models.CharField(max_length=28)),
                ('addressline1', models.CharField(max_length=28)),
                ('addressline2', models.CharField(max_length=28)),
                ('place', models.CharField(max_length=28)),
                ('pin', models.CharField(max_length=28)),
                ('password', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=28)),
                ('catagory', models.CharField(choices=[('normal', 'normal'), ('mixed', 'mixed')], max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstdose_status', models.BooleanField(default=False)),
                ('seconddose_status', models.BooleanField(default=False)),
                ('fdate_approved', models.DateField(blank=True, null=True)),
                ('sdate_approved', models.DateField(blank=True, null=True)),
                ('cattleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cattle')),
                ('diseaseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cattletagno', models.CharField(max_length=10)),
                ('farmer_name', models.CharField(max_length=255)),
                ('disease', models.CharField(max_length=40)),
                ('vaccine', models.CharField(max_length=28)),
                ('date_requested', models.DateField()),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('dose', models.PositiveSmallIntegerField(default=0)),
                ('status', models.BooleanField(choices=[(False, 'Pending'), (True, 'Approved')], default=False)),
                ('cattleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cattle')),
                ('diseaseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.disease')),
                ('farmerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.farmer')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vaccines'),
        ),
        migrations.AddField(
            model_name='cattle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.farmer'),
        ),
        migrations.CreateModel(
            name='ArtificialInsemination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField()),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('pregnant_status', models.BooleanField(blank=True, choices=[(True, 'Pregnant'), (False, 'Not Pregnant'), (None, 'Pending Pregnancy')], default=None, null=True)),
                ('cattleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cattle')),
                ('farmerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.farmer')),
            ],
        ),
    ]
