# Generated by Django 4.1.7 on 2023-04-23 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bull_vaccines_manfacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='artificialinsemination',
            name='bull',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.bull'),
        ),
    ]
