# Generated by Django 4.1.7 on 2023-04-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_artificialinsemination_bull'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination_s',
            name='eligibility_yd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccination_s',
            name='ldate_approved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
